server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    activate: prod
  datasource:
    url: jdbc:postgresql://ep-dark-cherry-a4c74yoi-pooler.us-east-1.aws.neon.tech/user_center?sslmode=require
    username: default
    password: 1bKszOt3FjlC
    driver-class-name: org.postgresql.Driver
table:
  name: Users_Prod
